version: "3.8"

services:
  traefik:
    image: traefik:v2.10
    command:
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--api.insecure=true"
    ports:
      - "80:80"
      - "8081:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml
    networks:
      - web

  front:
    build: ./web
    container_name: ${APP_NAME}-front
    volumes:
      - ./web:/app
      - /app/node_modules
    environment:
      - WEB_PORT=${WEB_PORT}
    depends_on:
      - api
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.front.rule=Host(`autocare.localhost`)"
      - "traefik.http.routers.front.entrypoints=web"
    networks:
      - web

  api:
    build:
      context: ./api
      args:
        API_PORT: ${API_PORT} ${API_PORT}
    environment:
      - API_PORT=${API_PORT}
    container_name: ${APP_NAME}-api
    volumes:
      - ./api:/app
      - /app/node_modules
    depends_on:
      - db
    ports:
      - ${API_PORT}:${API_PORT}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`api.autocare.localhost`)"
      - "traefik.http.routers.api.entrypoints=web"
    networks:
      - web

  db:
    container_name: ${APP_NAME}-db
    image: postgres:15
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - web

  pgadmin:
    image: dpage/pgadmin4
    container_name: ${APP_NAME}-dbadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PG_ADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PG_ADMIN_PASS}
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.phpmyadmin.rule=Host(`db.autocare.localhost`)"
      - "traefik.http.routers.phpmyadmin.entrypoints=web"
    depends_on:
      - db
    networks:
      - web

  mailhog:
    image: mailhog/mailhog
    container_name: autocare-mailhog
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mailhog.rule=Host(`mail.autocare.localhost`)"
      - "traefik.http.routers.mailhog.entrypoints=web"
      - "traefik.http.services.mailhog.loadbalancer.server.port=8025"

    depends_on:
      - api
volumes:
  pgdata:

networks:
  web:
    external: false
