# Build stage
FROM node:22-slim AS builder

WORKDIR /app

# install deps
COPY package.json ./

RUN npm install

COPY . .

RUN npm run build

# build stage
FROM node:22-alpine AS runner

WORKDIR /app

# Only necessary built bundles && node_modules
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/package.json package.json

COPY package*.json ./

EXPOSE 8000

CMD [ "node", "-r","tsconfig-paths/register", "dist/index.js" ]